# Generated by Django 5.0.7 on 2024-08-12 15:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TravelGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('travel_name', models.CharField(max_length=15)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('invite_code', models.CharField(max_length=6, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=5, null=True)),
                ('travel_type', models.CharField(max_length=30, null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TravelPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('play', 'PLAY'), ('eat', 'EAT'), ('stay', 'STAY'), ('others', 'OTHERS')], max_length=10)),
                ('place', models.CharField(max_length=200)),
                ('address', models.CharField(blank=True, max_length=500, null=True)),
                ('description', models.TextField()),
                ('date', models.DateField(blank=True, null=True)),
                ('plan_start_time', models.TimeField(blank=True, null=True)),
                ('plan_end_time', models.TimeField(blank=True, null=True)),
                ('like_count', models.PositiveIntegerField(default=0)),
                ('comment_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('travel_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='travel_plans', to='plans.travelgroup')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_plans', to='plans.userprofile')),
            ],
        ),
        migrations.AddField(
            model_name='travelgroup',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_travel_groups', to='plans.userprofile'),
        ),
        migrations.AddField(
            model_name='travelgroup',
            name='members',
            field=models.ManyToManyField(related_name='joined_travel_groups', to='plans.userprofile'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('travel_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='plans.travelplan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plans.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('travel_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='plans.travelplan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plans.userprofile')),
            ],
            options={
                'unique_together': {('user', 'travel_plan')},
            },
        ),
    ]
