# Generated by Django 4.2.10 on 2024-08-13 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plans", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="travelgroup",
            name="has_travel_plans",
            field=models.BooleanField(default=False),
        ),
    ]
