# Generated by Django 5.0.7 on 2024-08-06 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plans", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="travelgroup",
            name="invite_code",
            field=models.CharField(max_length=6, null=True),
        ),
    ]
