# Generated by Django 4.2.10 on 2024-08-13 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plans", "0002_travelgroup_has_travel_plans"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="travelgroup",
            name="has_travel_plans",
        ),
        migrations.AddField(
            model_name="travelplan",
            name="has_travel_plans",
            field=models.BooleanField(default=False),
        ),
    ]
