# Generated by Django 5.0.7 on 2024-08-06 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plans", "0003_alter_travelgroup_invite_code"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="travelgroup",
            name="user_profile",
        ),
        migrations.AddField(
            model_name="travelgroup",
            name="user_profiles",
            field=models.ManyToManyField(
                related_name="travel_groups", to="plans.userprofile"
            ),
        ),
    ]
