# Generated by Django 4.2.10 on 2024-08-13 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("plans", "0003_remove_travelgroup_has_travel_plans_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="travelplan",
            name="has_travel_plans",
        ),
    ]
