# Generated by Django 5.0.7 on 2024-08-09 09:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0004_remove_travelgroup_user_profile_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='travelgroup',
            name='user_profiles',
        ),
        migrations.AddField(
            model_name='travelgroup',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_travel_groups', to='plans.userprofile'),
        ),
        migrations.AddField(
            model_name='travelgroup',
            name='members',
            field=models.ManyToManyField(related_name='joined_travel_groups', to='plans.userprofile'),
        ),
        migrations.CreateModel(
            name='TravelPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('play', 'PLAY'), ('eat', 'EAT'), ('stay', 'STAY'), ('others', 'OTHERS')], max_length=10)),
                ('place', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_plans', to='plans.userprofile')),
                ('travel_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='travel_plans', to='plans.travelgroup')),
            ],
        ),
    ]
