# Generated by Django 4.2.10 on 2024-08-13 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plans", "0004_remove_travelplan_has_travel_plans"),
    ]

    operations = [
        migrations.AddField(
            model_name="travelplan",
            name="airplane_text",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
