# Generated by Django 5.0.7 on 2024-08-10 06:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0005_remove_travelgroup_user_profiles_travelgroup_creator_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelplan',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='travelplan',
            name='time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
