# Generated by Django 5.0.7 on 2024-08-10 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0006_travelplan_date_travelplan_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travelplan',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='travelplan',
            name='time',
            field=models.TimeField(),
        ),
    ]
