# Generated by Django 5.0.7 on 2024-08-10 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0007_alter_travelplan_date_alter_travelplan_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travelplan',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='travelplan',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
