# Generated by Django 5.0.7 on 2024-08-10 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0008_alter_travelplan_date_alter_travelplan_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='travelplan',
            name='time',
        ),
        migrations.AddField(
            model_name='travelplan',
            name='plan_end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='travelplan',
            name='plan_start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
