# Generated by Django 5.0.7 on 2024-08-11 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0009_remove_travelplan_time_travelplan_plan_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelplan',
            name='address',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
