# Generated by Django 5.0.7 on 2024-08-11 23:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0010_travelplan_address_travelplan_comment_count_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='like',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='like',
            name='travel_plan',
        ),
        migrations.RemoveField(
            model_name='like',
            name='user',
        ),
        migrations.CreateModel(
            name='PlanLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liked_at', models.DateTimeField(auto_now_add=True)),
                ('travel_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plans.travelplan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plans.userprofile')),
            ],
            options={
                'unique_together': {('user', 'travel_plan')},
            },
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
