# Generated by Django 5.0.7 on 2024-08-12 00:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0012_remove_travelplan_comment_count_alter_planlike_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelplan',
            name='comment_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='planlike',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plans.userprofile'),
        ),
        migrations.AlterField(
            model_name='travelplan',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_plans', to='plans.userprofile'),
        ),
    ]
